name: Release silvio on pypi
on: push

jobs:
  build:
    name: Build and publish silvio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persistent-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build silvio
        run: python -m build
      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish silvio to PyPI
    if: startWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/silvio/
    permissions:
      id-token: write

    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish silvio to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1